export { default as InboxPanelContent }      from './InboxPanelContent';
export { default as InvoicesPanelContent }   from './InvoicesPanelContent';
export { default as CalendarPanelContent }   from './CalendarPanelContent';
export { default as ContractsPanelContent }  from './ContractsPanelContent';
export { default as CallsPanelContent }      from './CallsPanelContent';
export { default as MessagesPanelContent }   from './MessagesPanelContent';
export { default as QuotesPanelContent }     from './QuotesPanelContent';
export { default as AuthorityPanelContent }  from './AuthorityPanelContent';
export { default as FinancePanelContent }    from './FinancePanelContent';
export { default as PlanPanelContent }       from './PlanPanelContent';
export { default as NotesPanelContent }      from './NotesPanelContent';
export { default as ReceiptsPanelContent }   from './ReceiptsPanelContent';
export type { PanelContentProps }            from './types';
