/**
 * Calls & Messages — mock data for visual review before migration 114 ships.
 *
 * Shapes match the Wave 7 schema (frontdesk_contacts, frontdesk_voicemails,
 * call_sessions) per the approved plan §7. Once the migration lands, the
 * store flips `useMockData` to false and these fixtures are no longer read.
 */

import type {
  FrontdeskContact,
  FrontdeskVoicemail,
  FrontdeskCallSession,
} from '@/types/calls-messages';

const SUITE_ID = '94b89098-c4bf-4419-a154-e18d9d53f993';

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

export const MOCK_CONTACTS: FrontdeskContact[] = [
  {
    contact_id: 'ct_01',
    suite_id: SUITE_ID,
    phone_e164: '+14155550142',
    display_name: 'Marcus Reilly',
    company: 'Reilly & Sons Roofing',
    email: 'marcus@reillyroof.com',
    status: 'active',
    total_calls: 14,
    last_call_summary: 'Quoted re-roof on Westside duplex; following up Friday.',
    last_seen_at: hoursAgo(2),
    notes: 'Pays net-15. Prefers texts before 9am.',
    tags: ['repeat', 'commercial'],
    created_at: daysAgo(120),
    updated_at: hoursAgo(2),
  },
  {
    contact_id: 'ct_02',
    suite_id: SUITE_ID,
    phone_e164: '+12065550199',
    display_name: 'Yvonne Park',
    company: 'Park Design Studio',
    email: 'yvonne@parkdesign.co',
    status: 'active',
    total_calls: 6,
    last_call_summary: 'Wants quote for kitchen remodel — needs rough number by Tuesday.',
    last_seen_at: hoursAgo(5),
    notes: null,
    tags: ['hot-lead'],
    created_at: daysAgo(45),
    updated_at: hoursAgo(5),
  },
  {
    contact_id: 'ct_03',
    suite_id: SUITE_ID,
    phone_e164: '+13105550168',
    display_name: 'Daniel Cho',
    company: null,
    email: null,
    status: 'active',
    total_calls: 2,
    last_call_summary: 'Asked about pricing for fence repair.',
    last_seen_at: daysAgo(1),
    notes: null,
    tags: [],
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  {
    contact_id: 'ct_04',
    suite_id: SUITE_ID,
    phone_e164: '+15035550127',
    display_name: 'Unknown caller',
    company: null,
    email: null,
    status: 'unconfirmed',
    total_calls: 1,
    last_call_summary: 'Caller did not provide a name.',
    last_seen_at: minutesAgo(38),
    notes: null,
    tags: [],
    created_at: minutesAgo(38),
    updated_at: minutesAgo(38),
  },
  {
    contact_id: 'ct_05',
    suite_id: SUITE_ID,
    phone_e164: '+18005551111',
    display_name: 'Spam — auto warranty',
    company: null,
    email: null,
    status: 'blocked',
    total_calls: 4,
    last_call_summary: 'Robocall, blocked.',
    last_seen_at: daysAgo(3),
    notes: 'Auto-warranty robocall.',
    tags: ['spam'],
    created_at: daysAgo(30),
    updated_at: daysAgo(3),
  },
  {
    contact_id: 'ct_06',
    suite_id: SUITE_ID,
    phone_e164: '+16175550144',
    display_name: 'Priya Subramanian',
    company: 'Beacon Hill HOA',
    email: 'priya@beaconhillhoa.org',
    status: 'active',
    total_calls: 9,
    last_call_summary: 'Annual gutter contract renewal — wants invoice this week.',
    last_seen_at: hoursAgo(20),
    notes: 'Board approval required for any work over $5k.',
    tags: ['contract'],
    created_at: daysAgo(200),
    updated_at: hoursAgo(20),
  },
];

export const MOCK_VOICEMAILS: FrontdeskVoicemail[] = [
  {
    voicemail_id: 'vm_01',
    suite_id: SUITE_ID,
    contact_id: 'ct_02',
    caller_name: 'Yvonne Park',
    callback_number: '+12065550199',
    call_reason: 'Kitchen remodel quote',
    call_summary:
      'Wants a rough quote for a kitchen remodel — about 180 sqft, keeping the existing footprint. Hoping to start before Memorial Day. Asked you to call her back today before 5pm.',
    urgency: 'high',
    wants_callback: true,
    audio_uri: 'https://example.com/vm/01.mp3',
    duration_seconds: 47,
    read_at: null,
    archived_at: null,
    created_at: minutesAgo(12),
  },
  {
    voicemail_id: 'vm_02',
    suite_id: SUITE_ID,
    contact_id: 'ct_04',
    caller_name: null,
    callback_number: '+15035550127',
    call_reason: 'Emergency leak',
    call_summary:
      'Caller said there is water coming through her ceiling and she needs someone today. Did not give a name. Number is good to call back.',
    urgency: 'high',
    wants_callback: true,
    audio_uri: 'https://example.com/vm/02.mp3',
    duration_seconds: 33,
    read_at: null,
    archived_at: null,
    created_at: minutesAgo(38),
  },
  {
    voicemail_id: 'vm_03',
    suite_id: SUITE_ID,
    contact_id: 'ct_01',
    caller_name: 'Marcus Reilly',
    callback_number: '+14155550142',
    call_reason: 'Westside duplex re-roof',
    call_summary:
      'Following up on the quote you sent. Wants to lock in next month if pricing still holds. No rush — call him back when you have a few minutes.',
    urgency: 'medium',
    wants_callback: true,
    audio_uri: 'https://example.com/vm/03.mp3',
    duration_seconds: 62,
    read_at: null,
    archived_at: null,
    created_at: hoursAgo(2),
  },
  {
    voicemail_id: 'vm_04',
    suite_id: SUITE_ID,
    contact_id: 'ct_06',
    caller_name: 'Priya Subramanian',
    callback_number: '+16175550144',
    call_reason: 'Annual gutter contract',
    call_summary:
      'Board approved the renewal at last night’s meeting. Asked you to send the updated invoice when convenient.',
    urgency: 'low',
    wants_callback: false,
    audio_uri: 'https://example.com/vm/04.mp3',
    duration_seconds: 28,
    read_at: hoursAgo(18),
    archived_at: null,
    created_at: hoursAgo(20),
  },
  {
    voicemail_id: 'vm_05',
    suite_id: SUITE_ID,
    contact_id: 'ct_03',
    caller_name: 'Daniel Cho',
    callback_number: '+13105550168',
    call_reason: 'Fence repair pricing',
    call_summary: 'Asked for ballpark pricing on a 40ft fence repair. Said no rush.',
    urgency: 'low',
    wants_callback: false,
    audio_uri: 'https://example.com/vm/05.mp3',
    duration_seconds: 19,
    read_at: daysAgo(1),
    archived_at: null,
    created_at: daysAgo(1),
  },
];

export const MOCK_CALL_SESSIONS: FrontdeskCallSession[] = [
  {
    call_session_id: 'cs_01',
    suite_id: SUITE_ID,
    contact_id: 'ct_02',
    conversation_id: 'conv_01',
    from_number: '+12065550199',
    to_number: '+14155550000',
    duration_seconds: 47,
    transcript_summary:
      'Yvonne left a voicemail about a kitchen remodel quote. Wants a callback today.',
    started_at: minutesAgo(12),
    ended_at: minutesAgo(11),
    direction: 'inbound',
  },
  {
    call_session_id: 'cs_02',
    suite_id: SUITE_ID,
    contact_id: 'ct_04',
    conversation_id: 'conv_02',
    from_number: '+15035550127',
    to_number: '+14155550000',
    duration_seconds: 33,
    transcript_summary: 'Anonymous caller reported a ceiling leak — left callback number.',
    started_at: minutesAgo(38),
    ended_at: minutesAgo(37),
    direction: 'inbound',
  },
  {
    call_session_id: 'cs_03',
    suite_id: SUITE_ID,
    contact_id: 'ct_01',
    conversation_id: 'conv_03',
    from_number: '+14155550142',
    to_number: '+14155550000',
    duration_seconds: 62,
    transcript_summary: 'Marcus following up on the Westside duplex quote.',
    started_at: hoursAgo(2),
    ended_at: hoursAgo(2),
    direction: 'inbound',
  },
  {
    call_session_id: 'cs_04',
    suite_id: SUITE_ID,
    contact_id: 'ct_01',
    conversation_id: 'conv_04',
    from_number: '+14155550000',
    to_number: '+14155550142',
    duration_seconds: 184,
    transcript_summary: 'Returned Marcus’s call — discussed timeline, agreed to email proposal.',
    started_at: hoursAgo(4),
    ended_at: hoursAgo(4),
    direction: 'outbound',
  },
  {
    call_session_id: 'cs_05',
    suite_id: SUITE_ID,
    contact_id: 'ct_06',
    conversation_id: 'conv_05',
    from_number: '+16175550144',
    to_number: '+14155550000',
    duration_seconds: 28,
    transcript_summary: 'Priya confirmed board approval on contract renewal.',
    started_at: hoursAgo(20),
    ended_at: hoursAgo(20),
    direction: 'inbound',
  },
  {
    call_session_id: 'cs_06',
    suite_id: SUITE_ID,
    contact_id: 'ct_03',
    conversation_id: 'conv_06',
    from_number: '+13105550168',
    to_number: '+14155550000',
    duration_seconds: 19,
    transcript_summary: 'Daniel asked about fence repair pricing.',
    started_at: daysAgo(1),
    ended_at: daysAgo(1),
    direction: 'inbound',
  },
  {
    call_session_id: 'cs_07',
    suite_id: SUITE_ID,
    contact_id: 'ct_05',
    conversation_id: 'conv_07',
    from_number: '+18005551111',
    to_number: '+14155550000',
    duration_seconds: 4,
    transcript_summary: 'Auto-blocked spam call.',
    started_at: daysAgo(3),
    ended_at: daysAgo(3),
    direction: 'inbound',
  },
];
