import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, Pressable, Image, ImageBackground } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { HubPageShell } from '@/components/founder-hub/HubPageShell';
import { resolveHubImage } from '@/data/founderHub/imageHelper';
import { supabase } from '@/lib/supabase';

const THEME = {
  bg: '#000000',
  surface: '#0a0a0a',
  surfaceHover: '#111111',
  border: 'rgba(255,255,255,0.06)',
  accent: '#3B82F6',
  accentMuted: 'rgba(59, 130, 246, 0.12)',
  text: {
    primary: '#ffffff',
    secondary: 'rgba(255,255,255,0.70)',
    muted: 'rgba(255,255,255,0.45)',
  },
};

// Daily brief data comes from Adam (research agent) + n8n daily workflows → Supabase receipts
type DailyBriefData = {
  id: string;
  date: string;
  title: string;
  bullets: string[];
  whyItMatters: string;
  ctas: { label: string; action: string; params?: any }[];
  imageKey: string;
  imageUrl?: string;
  metrics?: { label: string; value: string; change: string; color?: string }[];
  focusAreas?: { title: string; description: string; icon?: string }[];
};

type PastBrief = { id: string; date: string; title: string; read: boolean };
type AiInsight = { id: string; icon: string; title: string; desc: string };

export default function DailyBriefScreen() {
  const [hoveredItem, setHoveredItem] = useState<string | null>(null);
  const [dailyBrief, setDailyBrief] = useState<DailyBriefData>({
    id: '',
    date: new Date().toISOString().split('T')[0],
    title: 'Your daily brief will appear here once Adam completes his research.',
    bullets: ['Connect your tools for personalized insights', 'Adam analyzes your business data daily', 'n8n workflows deliver fresh intelligence each morning'],
    whyItMatters: 'Daily briefs are generated by Adam (research agent) using your connected tool data and industry intelligence.',
    ctas: [{ label: 'Discuss with Ava', action: 'OPEN_STUDIO' }],
    imageKey: 'pallet-yard',
  });
  const [pastBriefs, setPastBriefs] = useState<PastBrief[]>([]);
  const [aiInsights, setAiInsights] = useState<AiInsight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch latest daily brief from Adam's research receipts
    const fetchBrief = supabase
      .from('receipts')
      .select('*')
      .or('action_type.like.adam.daily_brief%,action_type.like.research.daily_brief%,action_type.like.founder_hub.brief%')
      .order('created_at', { ascending: false })
      .limit(1)
      .then(({ data }) => {
        if (data?.[0]?.payload) {
          const p = data[0].payload;
          setDailyBrief({
            id: data[0].id ?? '',
            date: data[0].created_at?.split('T')[0] ?? new Date().toISOString().split('T')[0],
            title: p.title ?? 'Daily Brief',
            bullets: p.bullets ?? p.key_points ?? [],
            whyItMatters: p.why_it_matters ?? p.summary ?? '',
            ctas: p.ctas ?? [{ label: 'Discuss with Ava', action: 'OPEN_STUDIO' }],
            imageKey: p.image_key ?? 'pallet-yard',
            imageUrl: p.image_url ?? p.results?.[0]?.image_url ?? undefined,
            metrics: p.metrics ?? undefined,
            focusAreas: p.focus_areas ?? p.action_items ?? undefined,
          });
        }
      });

    // Fetch past briefs (last 5)
    const fetchPast = supabase
      .from('receipts')
      .select('id,created_at,payload')
      .or('action_type.like.adam.daily_brief%,action_type.like.research.daily_brief%,action_type.like.founder_hub.brief%')
      .order('created_at', { ascending: false })
      .range(1, 5)
      .then(({ data }) => {
        if (data && data.length > 0) {
          setPastBriefs(data.map((r: any, idx: number) => ({
            id: r.id ?? `past-${idx}`,
            date: r.created_at?.split('T')[0] ?? '',
            title: r.payload?.title ?? 'Past brief',
            read: true,
          })));
        }
      });

    // Fetch AI insights from Adam's pulse/insight receipts
    const fetchInsights = supabase
      .from('receipts')
      .select('id,payload')
      .or('action_type.like.adam.pulse%,action_type.like.research.insight%,action_type.like.founder_hub.insight%')
      .order('created_at', { ascending: false })
      .limit(3)
      .then(({ data }) => {
        if (data && data.length > 0) {
          const iconMap: Record<string, string> = {
            opportunity: 'trending-up-outline',
            risk: 'warning-outline',
            strategic: 'bulb-outline',
          };
          setAiInsights(data.map((r: any, idx: number) => {
            const p = r.payload ?? {};
            return {
              id: r.id ?? `insight-${idx}`,
              icon: iconMap[p.insight_type] ?? ['trending-up-outline', 'warning-outline', 'bulb-outline'][idx % 3],
              title: p.title ?? 'Insight',
              desc: p.summary ?? p.description ?? '',
            };
          }));
        }
      });

    Promise.allSettled([fetchBrief, fetchPast, fetchInsights]).then(() => setLoading(false));
  }, []);

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
  };

  const formatShortDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  const rightRail = (
    <View style={styles.railContent}>
      <Text style={styles.railTitle}>Past Briefs</Text>
      <View style={styles.pastBriefsList}>
        {pastBriefs.map((brief) => (
          <Pressable
            key={brief.id}
            style={[
              styles.pastBriefItem,
              hoveredItem === `brief-${brief.id}` && styles.pastBriefItemHover,
            ]}
            onHoverIn={() => setHoveredItem(`brief-${brief.id}`)}
            onHoverOut={() => setHoveredItem(null)}
          >
            <View style={styles.pastBriefLeft}>
              <Text style={styles.pastBriefDate}>{formatShortDate(brief.date)}</Text>
              {!brief.read && <View style={styles.unreadDot} />}
            </View>
            <Text style={styles.pastBriefTitle} numberOfLines={2}>{brief.title}</Text>
          </Pressable>
        ))}
      </View>

      <View style={styles.railDivider} />

      <Text style={styles.railTitle}>AI Insights</Text>
      <View style={styles.insightsList}>
        {aiInsights.map((insight) => (
          <View key={insight.id} style={styles.insightCard}>
            <View style={styles.insightIcon}>
              <Ionicons name={insight.icon} size={16} color={THEME.accent} />
            </View>
            <View style={styles.insightContent}>
              <Text style={styles.insightTitle}>{insight.title}</Text>
              <Text style={styles.insightDesc}>{insight.desc}</Text>
            </View>
          </View>
        ))}
      </View>
    </View>
  );

  return (
    <HubPageShell rightRail={rightRail}>
      <View style={styles.header}>
        <Text style={styles.pageTitle}>Daily Brief</Text>
        <Text style={styles.pageSubtitle}>AI-curated intelligence for your business</Text>
      </View>

      <View style={styles.todayCard}>
        <ImageBackground
          source={resolveHubImage(dailyBrief.imageUrl, dailyBrief.imageKey)}
          style={styles.heroImage}
          imageStyle={styles.heroImageStyle}
        >
          <LinearGradient
            colors={['rgba(0,0,0,0.2)', 'rgba(0,0,0,0.85)', 'rgba(0,0,0,0.98)']}
            style={styles.heroOverlay}
          >
            <View style={styles.todayBadge}>
              <Ionicons name="sunny" size={14} color={THEME.accent} />
              <Text style={styles.todayBadgeText}>Today's Brief</Text>
            </View>
            <Text style={styles.heroDate}>{formatDate(dailyBrief.date)}</Text>
            <Text style={styles.heroTitle}>{dailyBrief.title}</Text>
            
            <View style={styles.bulletsList}>
              {dailyBrief.bullets.map((bullet, idx) => (
                <View key={idx} style={styles.bulletRow}>
                  <View style={styles.bulletDot} />
                  <Text style={styles.bulletText}>{bullet}</Text>
                </View>
              ))}
            </View>

            <Text style={styles.whyMatters}>{dailyBrief.whyItMatters}</Text>

            <View style={styles.heroActions}>
              <Pressable
                style={[styles.primaryBtn, hoveredItem === 'discuss' && styles.primaryBtnHover]}
                onHoverIn={() => setHoveredItem('discuss')}
                onHoverOut={() => setHoveredItem(null)}
              >
                <Ionicons name="chatbubble-outline" size={16} color="#FFFFFF" />
                <Text style={styles.primaryBtnText}>Discuss with Ava</Text>
              </Pressable>
              <Pressable
                style={[styles.secondaryBtn, hoveredItem === 'save' && styles.secondaryBtnHover]}
                onHoverIn={() => setHoveredItem('save')}
                onHoverOut={() => setHoveredItem(null)}
              >
                <Ionicons name="bookmark-outline" size={16} color={THEME.accent} />
                <Text style={styles.secondaryBtnText}>Save takeaway</Text>
              </Pressable>
            </View>
          </LinearGradient>
        </ImageBackground>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Key Metrics Today</Text>
        <View style={styles.metricsGrid}>
          {dailyBrief.metrics && dailyBrief.metrics.length > 0 ? (
            dailyBrief.metrics.map((m: any, idx: number) => (
              <View key={idx} style={styles.metricCard}>
                <Text style={styles.metricLabel}>{m.label}</Text>
                <Text style={styles.metricValue}>{m.value}</Text>
                <Text style={[styles.metricChange, m.color ? { color: m.color } : undefined]}>{m.change}</Text>
              </View>
            ))
          ) : (
            <View style={styles.metricCard}>
              <View style={{ alignItems: 'center', gap: 8, paddingVertical: 8 }}>
                <Ionicons name="analytics-outline" size={24} color={THEME.text.muted} />
                <Text style={styles.metricLabel}>Connect your accounts to see live metrics</Text>
                <Text style={[styles.metricChange, { color: THEME.accent }]}>Finance Hub → Connections</Text>
              </View>
            </View>
          )}
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Today's Focus Areas</Text>
        <View style={styles.focusGrid}>
          {dailyBrief.focusAreas && dailyBrief.focusAreas.length > 0 ? (
            dailyBrief.focusAreas.map((focus: any, idx: number) => {
              const iconColors = ['rgba(59, 130, 246, 0.12)', 'rgba(251, 191, 36, 0.12)', 'rgba(52, 211, 153, 0.12)'];
              const textColors = [THEME.accent, '#fbbf24', '#34d399'];
              const icons: Array<'flag-outline' | 'alert-circle-outline' | 'trending-up-outline'> = ['flag-outline', 'alert-circle-outline', 'trending-up-outline'];
              return (
                <Pressable
                  key={idx}
                  style={[styles.focusCard, hoveredItem === `focus-${idx}` && styles.focusCardHover]}
                  onHoverIn={() => setHoveredItem(`focus-${idx}`)}
                  onHoverOut={() => setHoveredItem(null)}
                >
                  <View style={[styles.focusIcon, { backgroundColor: iconColors[idx % 3] }]}>
                    <Ionicons name={focus.icon ?? icons[idx % 3]} size={20} color={textColors[idx % 3]} />
                  </View>
                  <Text style={styles.focusTitle}>{focus.title}</Text>
                  <Text style={styles.focusDesc}>{focus.description}</Text>
                </Pressable>
              );
            })
          ) : (
            <View style={[styles.focusCard, { alignItems: 'center', justifyContent: 'center', paddingVertical: 24 }]}>
              <Ionicons name="sunny-outline" size={24} color={THEME.text.muted} />
              <Text style={[styles.focusTitle, { textAlign: 'center' }]}>Focus areas appear with your first brief</Text>
              <Text style={[styles.focusDesc, { textAlign: 'center' }]}>Adam analyzes your data daily to surface what matters most.</Text>
            </View>
          )}
        </View>
      </View>
    </HubPageShell>
  );
}

const styles = StyleSheet.create({
  header: {
    marginBottom: 32,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: THEME.text.primary,
    marginBottom: 8,
  },
  pageSubtitle: {
    fontSize: 15,
    color: THEME.text.muted,
  },
  todayCard: {
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 32,
  },
  heroImage: {
    width: '100%',
    minHeight: 380,
  },
  heroImageStyle: {
    borderRadius: 16,
  },
  heroOverlay: {
    flex: 1,
    padding: 32,
    justifyContent: 'flex-end',
  },
  todayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  todayBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: THEME.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  heroDate: {
    fontSize: 13,
    color: THEME.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: THEME.text.primary,
    lineHeight: 34,
    marginBottom: 20,
    maxWidth: 600,
  },
  bulletsList: {
    gap: 12,
    marginBottom: 16,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: THEME.accent,
    marginTop: 7,
  },
  bulletText: {
    fontSize: 15,
    color: THEME.text.secondary,
    lineHeight: 22,
    flex: 1,
  },
  whyMatters: {
    fontSize: 14,
    color: THEME.text.muted,
    fontStyle: 'italic',
    marginBottom: 24,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 12,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: THEME.accent,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  primaryBtnHover: {
    opacity: 0.9,
    transform: [{ scale: 1.02 }],
  },
  primaryBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  secondaryBtnHover: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  secondaryBtnText: {
    fontSize: 14,
    fontWeight: '500',
    color: THEME.accent,
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: THEME.text.primary,
    marginBottom: 16,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  metricCard: {
    flex: 1,
    minWidth: 160,
    backgroundColor: THEME.surface,
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  metricLabel: {
    fontSize: 12,
    color: THEME.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 24,
    fontWeight: '700',
    color: THEME.text.primary,
    marginBottom: 4,
  },
  metricChange: {
    fontSize: 13,
    color: THEME.text.muted,
  },
  focusGrid: {
    gap: 12,
  },
  focusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    backgroundColor: THEME.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  focusCardHover: {
    backgroundColor: THEME.surfaceHover,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  focusIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  focusTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: THEME.text.primary,
    marginBottom: 2,
  },
  focusDesc: {
    fontSize: 13,
    color: THEME.text.muted,
  },
  railContent: {
    gap: 24,
  },
  railTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: THEME.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  pastBriefsList: {
    gap: 8,
  },
  pastBriefItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 12,
    borderRadius: 8,
    backgroundColor: THEME.surface,
  },
  pastBriefItemHover: {
    backgroundColor: THEME.surfaceHover,
  },
  pastBriefLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 60,
  },
  pastBriefDate: {
    fontSize: 12,
    color: THEME.text.muted,
  },
  unreadDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: THEME.accent,
  },
  pastBriefTitle: {
    flex: 1,
    fontSize: 13,
    color: THEME.text.secondary,
    lineHeight: 18,
  },
  railDivider: {
    height: 1,
    backgroundColor: THEME.border,
  },
  insightsList: {
    gap: 12,
  },
  insightCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 12,
    backgroundColor: THEME.surface,
    borderRadius: 10,
  },
  insightIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: THEME.accentMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightContent: {
    flex: 1,
  },
  insightTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: THEME.text.primary,
    marginBottom: 4,
  },
  insightDesc: {
    fontSize: 12,
    color: THEME.text.muted,
    lineHeight: 16,
  },
});
