/**
 * printDocument — Cross-platform print and share utilities for finance documents.
 *
 * Platform strategy:
 * - Web: expo-print uses window.print(), expo-sharing uses Web Share API
 * - Native: expo-print uses native print dialog, expo-sharing uses native share sheet
 */
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

interface InvoicePrintData {
  invoiceNumber: string;
  customerName: string;
  customerEmail?: string;
  amount: string;
  status: string;
  dueDate?: string;
  createdDate: string;
  lines?: { description: string; amount: string }[];
}

/** Generate HTML for invoice printing. */
function generateInvoiceHtml(invoice: InvoicePrintData): string {
  const linesHtml = (invoice.lines ?? [])
    .map(
      (line) => `
      <tr>
        <td style="padding: 8px 0; border-bottom: 1px solid #eee;">${line.description}</td>
        <td style="padding: 8px 0; border-bottom: 1px solid #eee; text-align: right;">${line.amount}</td>
      </tr>`
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Invoice ${invoice.invoiceNumber}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1a1a1a; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
        .logo { font-size: 24px; font-weight: 700; color: #0a0a0c; }
        .invoice-info { text-align: right; }
        .invoice-number { font-size: 20px; font-weight: 600; color: #3B82F6; }
        .status { display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: 600; text-transform: uppercase; }
        .status-paid { background: #dcfce7; color: #16a34a; }
        .status-open { background: #fef3c7; color: #d97706; }
        .status-draft { background: #f3f4f6; color: #6b7280; }
        .customer { margin-bottom: 30px; }
        .customer-name { font-size: 16px; font-weight: 600; }
        .customer-email { color: #6b7280; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th { text-align: left; padding: 12px 0; border-bottom: 2px solid #e5e7eb; font-weight: 600; }
        th:last-child { text-align: right; }
        .total { font-size: 24px; font-weight: 700; text-align: right; margin-top: 20px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">Aspire</div>
        <div class="invoice-info">
          <div class="invoice-number">${invoice.invoiceNumber}</div>
          <div>Created: ${invoice.createdDate}</div>
          ${invoice.dueDate ? `<div>Due: ${invoice.dueDate}</div>` : ''}
          <div class="status status-${invoice.status}">${invoice.status}</div>
        </div>
      </div>
      <div class="customer">
        <div class="customer-name">${invoice.customerName}</div>
        ${invoice.customerEmail ? `<div class="customer-email">${invoice.customerEmail}</div>` : ''}
      </div>
      ${linesHtml ? `
      <table>
        <thead>
          <tr><th>Description</th><th>Amount</th></tr>
        </thead>
        <tbody>${linesHtml}</tbody>
      </table>` : ''}
      <div class="total">Total: ${invoice.amount}</div>
      <div class="footer">
        Generated by Aspire &mdash; Governed AI Execution Infrastructure
      </div>
    </body>
    </html>
  `;
}

/** Print an invoice using native print dialog. */
export async function printInvoice(invoice: InvoicePrintData): Promise<void> {
  const html = generateInvoiceHtml(invoice);
  await Print.printAsync({ html });
}

/** Generate a PDF file from an invoice. Returns the file URI. */
export async function generateInvoicePdf(invoice: InvoicePrintData): Promise<string> {
  const html = generateInvoiceHtml(invoice);
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

/** Share a document file using native share sheet. */
export async function shareDocument(uri: string, title?: string): Promise<void> {
  const available = await Sharing.isAvailableAsync();
  if (!available) {
    // Fallback: open in new tab on web
    if (Platform.OS === 'web' && typeof window !== 'undefined') {
      window.open(uri, '_blank');
    }
    return;
  }

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: title ?? 'Share Document',
    UTI: 'com.adobe.pdf',
  });
}

/** Print and/or share an invoice — convenience wrapper. */
export async function shareInvoice(invoice: InvoicePrintData): Promise<void> {
  const pdfUri = await generateInvoicePdf(invoice);
  await shareDocument(pdfUri, `Invoice ${invoice.invoiceNumber}`);
}
