#!/usr/bin/env bash
# TypeForge: Generate TypeScript types from backend OpenAPI spec + Supabase schema
# Usage: bash scripts/gen-types.sh [--check]
# With --check: exits 1 if generated types differ from committed (CI drift detection)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TYPES_DIR="$PROJECT_ROOT/types"
BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"
SUPABASE_PROJECT_ID="${SUPABASE_PROJECT_ID:-qtuehjqlcmfcascqjjhc}"
CHECK_MODE="${1:-}"

mkdir -p "$TYPES_DIR"

echo "TypeForge (Desktop): Generating types..."
echo ""

# 1. Fetch OpenAPI spec from backend
echo "  [1/2] Fetching OpenAPI spec from $BACKEND_URL/openapi.json..."
if curl -sf "$BACKEND_URL/openapi.json" -o "$TYPES_DIR/openapi.json" 2>/dev/null; then
    echo "  OK    OpenAPI spec saved"
    # Generate API types
    if npx openapi-typescript "$TYPES_DIR/openapi.json" -o "$TYPES_DIR/api.generated.ts" 2>/dev/null; then
        echo "  OK    API types generated: types/api.generated.ts"
    else
        echo "  WARN  openapi-typescript generation failed"
    fi
else
    echo "  WARN  Backend not running — skipping OpenAPI type generation"
    if [ ! -f "$TYPES_DIR/api.generated.ts" ]; then
        echo "        No cached API types found. Start backend first."
    else
        echo "        Using cached types/api.generated.ts"
    fi
fi

# 2. Generate Supabase types
echo "  [2/2] Generating Supabase types..."
if command -v supabase &>/dev/null; then
    if supabase gen types typescript --project-id "$SUPABASE_PROJECT_ID" > "$TYPES_DIR/supabase.generated.ts.tmp" 2>/dev/null; then
        # Add header
        {
            echo "// Auto-generated by Supabase CLI — DO NOT EDIT"
            echo "// Regenerate: bash scripts/gen-types.sh"
            echo ""
            cat "$TYPES_DIR/supabase.generated.ts.tmp"
        } > "$TYPES_DIR/supabase.generated.ts"
        rm "$TYPES_DIR/supabase.generated.ts.tmp"
        echo "  OK    Supabase types generated: types/supabase.generated.ts"
    else
        echo "  WARN  Supabase CLI auth issue — using cached types"
    fi
else
    echo "  WARN  Supabase CLI not installed — using cached types"
fi

echo ""

# Check mode: compare generated types against committed
if [ "$CHECK_MODE" = "--check" ]; then
    echo "TypeForge: Drift detection..."
    DRIFT=0

    for f in api.generated.ts supabase.generated.ts; do
        if [ -f "$TYPES_DIR/$f" ]; then
            if ! git diff --quiet "$TYPES_DIR/$f" 2>/dev/null; then
                echo "  DRIFT  $f differs from committed version"
                DRIFT=1
            else
                echo "  OK     $f matches committed"
            fi
        fi
    done

    if [ "$DRIFT" -eq 1 ]; then
        echo ""
        echo "ERR: Type drift detected! Run 'bash scripts/gen-types.sh' and commit."
        exit 1
    fi

    echo ""
    echo "TypeForge: No drift detected."
fi

echo "TypeForge (Desktop): Done."
