// components/call-room/layers/manifest.ts
//
// Layer manifest for the Call Room office background.
//
// 2-layer parallax design (generated by scripts/slice-call-room-layers.mjs):
//
//   bg-far  — full image, alpha=1, foreground regions cheaply inpainted
//             with a heavy blur of the original. Static (parallaxRange=0)
//             so the room feels anchored.
//
//   fg-near — foreground content only with sharp original color and a
//             smooth alpha ramp. Translates with the cursor; reveals
//             bg-far's inpainted fill when it moves.
//
// At rest the composite is bit-identical to the source photo because
// fg-near's RGB matches bg-far's RGB everywhere it has alpha < 1.
//
// scale > 1 oversizes each layer so parallax travel never exposes the
// canvas edge.

export interface LayerSpec {
  src: number;
  parallaxRange: number; // px max translate when cursor is at viewport edge
  zIndex: number;
  opacity: number;
  scale: number;
}

export const layers: LayerSpec[] = [
  {
    src: require('./bg-far.webp'),
    parallaxRange: 0, // anchor — never moves
    zIndex: 0,
    opacity: 1,
    scale: 1.06,
  },
  {
    src: require('./fg-near.webp'),
    // 20px stays comfortably inside the 50px inpaint blur radius so the
    // revealed sliver behind the foreground always shows plausible color.
    parallaxRange: 20,
    zIndex: 1,
    opacity: 1,
    scale: 1.08,
  },
];
