// components/call-room/layers/manifest.ts
//
// Layer manifest for the Call Room office background.
//
// M2: 4 depth-sliced layers from the same source office photo, generated by
// scripts/slice-call-room-layers.mjs using a depth map. Each layer carries
// only the pixels in its depth band (alpha gradient), so they composite back
// to the original. Per-layer parallaxRange creates the depth illusion as the
// cursor moves: far layers stay still, near layers translate the most.
//
// scale > 1 oversizes each layer so parallax translation never exposes the
// canvas edge.

export interface LayerSpec {
  src: number;
  parallaxRange: number; // px max translate when cursor is at viewport edge
  zIndex: number;
  opacity: number;
  scale: number;
}

export const layers: LayerSpec[] = [
  {
    src: require('./bg-far.webp'),
    parallaxRange: 0, // anchor — never moves
    zIndex: 0,
    opacity: 1,
    scale: 1.06,
  },
  {
    src: require('./bg-mid.webp'),
    parallaxRange: 8,
    zIndex: 1,
    opacity: 1,
    scale: 1.06,
  },
  {
    src: require('./bg-near.webp'),
    parallaxRange: 16,
    zIndex: 2,
    opacity: 1,
    scale: 1.07,
  },
  {
    src: require('./fg-near.webp'),
    parallaxRange: 28,
    zIndex: 3,
    opacity: 1,
    scale: 1.08,
  },
];
